# Generated by Django 2.2.7 on 2019-12-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('thumbnail', models.ImageField(null=True, upload_to='', verbose_name='サムネイル')),
            ],
        ),
    ]
