# Generated by Django 2.2.7 on 2019-12-09 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': '記事', 'verbose_name_plural': '記事一覧'},
        ),
        migrations.AlterModelTable(
            name='entry',
            table='entry',
        ),
    ]
